version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - 2181:2181
        volumes:
          - ~/work/xm-online/volumes/zookeeper:/opt/zookeeper-3.4.6/data
    kafka:
        image: wurstmeister/kafka:2.12-2.1.1
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LOG_DIRS: /kafka/kafka-logs-1
        ports:
            - 9092:9092
        volumes:
            - ~/work/xm-online/volumes/kafka:/kafka/kafka-logs-1

