version: '2'
services:
    zookeeper:
        image: zookeeper:3.8.1
        ports:
          - 2181:2181
          - 2888:2888
          - 3888:3888
        volumes:
          - ~/work/xm-online/volumes/zookeeper:/opt/zookeeper/data
    kafka:
        image: wurstmeister/kafka:2.13-2.8.1
        environment:
            KAFKA_LOG_DIRS: /kafka/kafka-logs-1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
        ports:
            - 9092:9092
        volumes:
            - ~/work/xm-online/volumes/kafka:/kafka/kafka-logs-1

