version: '2'
services:
    postgresql:
        image: postgres:12.10
        volumes:
             - ~/work/xm-online/volumes/postgresql/:/var/lib/postgresql/data/
        environment:
            - TZ=Europe/Zurich
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
